
version: '3.3'

services:
   mongodb:
     image: "mongo"
     volumes:
        - data:/data/db
   backend: 
     build: ./server
     ports:
       - "4000:4000"
     volumes:
       - logs:/pictify/backend/logs
       - ./server:/pictify/backend
       - /pictify/backend/node_modules
     depends_on:
       - mongodb
   frontend:
     build: ./client
     ports:
       - "3000:3000"
     volumes:
       - ./client/src:/pictify/frontend/src
     stdin_open: true
     tty: true
     depends_on:
        - backend

volumes:
   data:
   logs:


